# Generated by Django 4.0.3 on 2022-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auction_category_watchlist_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
        migrations.AlterField(
            model_name='auction',
            name='highest_bidder',
            field=models.CharField(max_length=200),
        ),
    ]
